name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - nb_conda_kernels
  - maturin
  - pip
  - pip:
    - scipy
    - scikit-learn
    - numpy
    - pandas
    - plotly
    - torch torchvision torchaudio
