name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - scipy
  - scikit-learn
  - pytoch
  - matplotlib
  - lets-plot
  - seaborn
  - maturin
  - pip:
    - numpy
    - pandas
    - plotly
